import os

PORT = int(os.getenv("QUIZ_PORT", "8080"))

SECRET_KEY = os.getenv("QUIZ_SECRET_KEY", "super-secret-quiz-key-2024")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 24  # 24 hours

ADMIN_USERNAME = "k2k1"
ADMIN_PASSWORD = "123123"

DATABASE_URL = os.getenv("QUIZ_DATABASE_URL", "sqlite+aiosqlite:///./data/quiz.db")

MAX_TEAMS = 2
QUESTIONS_PER_GAME = 12
ANSWER_TIME_SECONDS = 20

# Room system
ROOM_INACTIVITY_TIMEOUT_SECONDS = 60
MAX_PLAYERS_PER_TEAM = 4
ROOM_CODE_LENGTH = 6
